### ISSUE TITLE
[BUG] No tools in the mod can level up (no levels, exp showing in the tool tip)

### ISSUE THREAD

**Issue by ZitherBai** [TheUnderTaker11/KitchenSink#10]
I'm sorry for reporting a bug and give you more work.

1. Check the picture: (can't level up the pickaxe, and it's unbreakable)
![image](https://user-images.githubusercontent.com/29588647/27364291-527d8798-566c-11e7-90b3-2ab3fb76034b.png)

2. Check the picture: (I think it should show the purpose and usage of the item, e.g. "gives your tool repair and can never break")
![image](https://user-images.githubusercontent.com/29588647/27364321-7c706e4e-566c-11e7-8fb8-7529070a6de5.png)

I tried the 1.20 and 1.18 version for a 1.10.2 modpack called "Craft of the Titans", and both of the versions doesn't give me the ability to level up my pickaxe.

Thanks,
Hope to hear from you ASAP. :P

**Comment by TheUnderTaker11** [comment]
Hm, did you craft the pickaxe? Or spawn it in creative?

**Comment by ZitherBai** [comment]
I crafted it, and I tried in creative, both of them doesn't work.

The creator of the pack changed the recipe because it's a little bit cheap, will that cause a problem?
![image](https://user-images.githubusercontent.com/29588647/27364553-def9a980-566d-11e7-940b-d49485a54459.png)

**Comment by ZitherBai** [comment]
That's the recipe of the tool rod
![image](https://user-images.githubusercontent.com/29588647/27364576-f45e37e6-566d-11e7-8030-4af4ab5cdf98.png)

**Comment by TheUnderTaker11** [comment]
Hm I think that would cause a problem, since I attach a lot of data on the craft itself. I should know how to fix this though. I'll need to make sure to also do the same for all other special crafts as well.

**Comment by ZitherBai** [comment]
Thank you soo much. :D

btw realised something, there is a number after the name of the pickaxe, which is different from the youtube video I watched before the recipe change. :P No sure if that will help.
![image](https://user-images.githubusercontent.com/29588647/27364713-c67f55fc-566e-11e7-9862-9108791d3cd2.png)

Hmm, do you know when will it be ready so I can enjoy the amazing lapis pickaxe in your mod? :D

**Comment by TheUnderTaker11** [comment]
That's just the ID Minecraft gives it. And honestly I made the recipe cheaper cause I figured people would just get the gods tool or do some tinkers tool and not even realize just how good that pick can be.
But I'll upload the file some time tomorrow. No idea when that will get added into your pack though.

**Comment by ZitherBai** [comment]
I think the recipe won't matters that much, I think your original design is good. If you can update the mod and post the file, I can manually change it in my modpack folder. :D

Thank you for your time and help. Really appreciate it.

**Comment by TheUnderTaker11** [comment]
No problem, I might be sluggish on new features but I'm always happy to fix whatever bugs may pop up.

**Comment by TheUnderTaker11** [comment]
Since I'm not sure what the recipe was changed with or any other circumstances, all I can do is upload this file and hope that it will fix it. I'm am fairly sure it should fix the problem though.
File has just been uploaded.

**Comment by ZitherBai** [comment]
Thank you. :D The new 1.21 version worked.
