### ISSUE TITLE
Killing Ghast by deflecting fireball with empty hand = NPE

### ISSUE THREAD

**Issue by Zeevian** [TheUnderTaker11/KitchenSink#5]
Was in the nether, killed 2 ghasts both caused a CTD due to the NPE of killing with nothing in my hand.

[crash-2017-04-03_21.49.44-server.txt](https://github.com/TheUnderTaker11/KitchenSink/files/891881/crash-2017-04-03_21.49.44-server.txt)

**Comment by TheUnderTaker11** [comment]
Huh... Very weird, but I'm on it.

**Comment by TheUnderTaker11** [comment]
Fixed crash, not sure how it wasn't crashing when you killed anything with an empty hand tbh. New version being uploaded now

**Comment by Zeevian** [comment]
thanks, that was the first thing I had killed with an empty hand tbh.  Died in the nether after killing a compressed ghast... you can imagine the chaos that took place.
