### ISSUE TITLE
angel ring crashes server

### ISSUE THREAD

**Issue by Agentx49** [TheUnderTaker11/KitchenSink#6]
crash report:[crash-2017-04-10_16.56.45-server.txt](https://github.com/TheUnderTaker11/KitchenSink/files/911464/crash-2017-04-10_16.56.45-server.txt)

modpack :https://www.dropbox.com/s/urljah0vcqh6uq5/Agentx8288%201.10.2.zip?dl=0

**Comment by TheUnderTaker11** [comment]
Was able to reproduce the crash on a testing server, will work on fixing it.

And any time you upload crash reports or things of the like, just paste the text to a place like https://pastebin.com/ so it is more readable and doesn't require a file download.

**Comment by Agentx49** [comment]
ok

**Comment by TheUnderTaker11** [comment]
Sent you fixed version, waiting for the OK to close issue and upload new file.

**Comment by TheUnderTaker11** [comment]
Said it's fixed.
