### ISSUE TITLE
[Suggestion] Fortune upgrade to the Lapis Pickaxe

### ISSUE THREAD

**Issue by Desempregago** [TheUnderTaker11/KitchenSink#7]
The title explains itself.

**Comment by TheUnderTaker11** [comment]
Just asking, are you aware of the fortune 5 upgrade you get later in the pick levels?

**Comment by Desempregago** [comment]
Really? I didn't know this

Em 11 de abr de 2017 16:20, Under <notifications@github.com> escreveu:

Just asking, are you aware of the fortune 5 upgrade you get later in the pick levels?

**Comment by TheUnderTaker11** [comment]
Oh no wonder, I just looked and I never put it on my wiki. My bad, I'll fix it when I get home. Would you still want that option to add up to fortune 3 before that level?(I'll look in code in about an hour to give an exact level it gives you fortune 5)

**Comment by Desempregago** [comment]
Don't worry, I wasn't aware of this function.
However, in which level the fortune kicks in?

Em 11 de abr de 2017 17:12, Under <notifications@github.com> escreveu:

Oh no wonder, I just looked and I never put it on my wiki. My bad, I'll fix it when I get home. Would you still want that option to add up to fortune 3 before that level?(I'll look in code in about an hour to give an exact level it gives you fortune 5)

**Comment by TheUnderTaker11** [comment]
As I said, when I get home in about 20 min now I'll look

**Comment by TheUnderTaker11** [comment]
You acquire the fortune 5 at pick level 5, and only get it if the silk touch enchant isn't on the pick.
