### ISSUE TITLE
Unbreakable tooltip not displaying for output of upgrade lapis pickaxe in NEI

### ISSUE THREAD

**Issue by Xavion3** [TheUnderTaker11/KitchenSink#9]
See [here](https://github.com/TheUnderTaker11/KitchenSink/blob/85853a16cceefbf1edd2214c20a27a8386372b5d/src/main/java/com/theundertaker11/kitchensink/ksitems/tools/LevelPick.java#L143), this doesn't check for dummyUnbreakable so consequently the unbreakable tooltip will never display.

**Comment by TheUnderTaker11** [comment]
Read and fixed this when you posted it, just forgot to reply and close. Not really worth pushing a whole version out, so it might be awhile before this fix is implemented.

**Comment by TheUnderTaker11** [comment]
Just uploaded file with fix.
